id = "avenger"
name = "Avenger"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "Avenger Language Support"
repository = "https://github.com/your-name/my-zed-extension"

[grammars.avenger]
repository = "https://github.com/avenger-vis/tree-sitter-avenger"
rev = "5e9ae3b5b7cbe6e10913e07468026ba7967950af"
